language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_00d31dd6a46c_key -iv $encrypted_00d31dd6a46c_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d

